version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017 
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo 
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: myadmin
      ME_CONFIG_BASICAUTH_PASSWORD: mypassword

volumes:
  mongo_data:
