version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./mytrain.db:/app/mytrain.db  # Persist SQLite database
    restart: unless-stopped
